### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by jmandel**

### CODE REVIEW

**Comment by jmandel** [comment]
@dennispatterson @kolkheang  I'd love to get this merged even with the following still outdated, since it represents a significant investment in update/fix/debug iterations, and it'd be good not to have a long-lived branch.

Still remaining:
```
$npm outdated

Package                          Current  Wanted  Latest  Location
copy-webpack-plugin                4.5.1   4.6.0   5.0.4  cds-hooks-sandbox
express                           4.16.2  4.17.1  4.17.1  cds-hooks-sandbox
file-loader                       1.1.11  1.1.11   4.2.0  cds-hooks-sandbox
jest-environment-jsdom-global      1.0.3   1.2.0   1.2.0  cds-hooks-sandbox
postcss-custom-properties          7.0.0   7.0.0   9.0.2  cds-hooks-sandbox
postcss-loader                     2.1.1   2.1.6   3.0.0  cds-hooks-sandbox
prop-types                        15.6.1  15.7.2  15.7.2  cds-hooks-sandbox
query-string                       5.1.0   5.1.1   6.8.2  cds-hooks-sandbox
raw-loader                         0.5.1   0.5.1   3.1.0  cds-hooks-sandbox
react-redux                        5.0.6   5.1.1   7.1.1  cds-hooks-sandbox
react-test-renderer               16.3.2  16.9.0  16.9.0  cds-hooks-sandbox
redux                              3.7.2   3.7.2   4.0.4  cds-hooks-sandbox
redux-mock-store                   1.4.0   1.5.3   1.5.3  cds-hooks-sandbox
sass-loader                        6.0.6   6.0.7   7.3.1  cds-hooks-sandbox
style-loader                      0.19.1  0.19.1   1.0.0  cds-hooks-sandbox
terra-application-header-layout    2.1.0   2.1.0  3.15.0  cds-hooks-sandbox
terra-base                        3.33.2  3.33.2  5.17.0  cds-hooks-sandbox
terra-button                       2.5.0  2.32.0  3.21.0  cds-hooks-sandbox
terra-card                         2.1.0  2.33.0  3.17.0  cds-hooks-sandbox
terra-content-container            2.4.0  2.33.0  3.16.0  cds-hooks-sandbox
terra-date-picker                  2.6.0  2.39.0  4.11.0  cds-hooks-sandbox
terra-dialog                       1.4.0  1.36.0  2.23.0  cds-hooks-sandbox
terra-form                         2.5.0  2.10.0  2.10.0  cds-hooks-sandbox
terra-form-checkbox                2.2.0  2.33.0  3.23.0  cds-hooks-sandbox
terra-form-field                   2.4.0  2.35.0  3.21.0  cds-hooks-sandbox
terra-form-input                   1.3.0  1.32.0  2.23.0  cds-hooks-sandbox
terra-form-select                  2.6.0   2.8.0  5.27.0  cds-hooks-sandbox
terra-heading                      2.1.0  2.32.0  4.15.0  cds-hooks-sandbox
terra-i18n-plugin                  2.0.0   2.2.0   2.2.0  cds-hooks-sandbox
terra-icon                         2.4.0  2.32.0  3.18.0  cds-hooks-sandbox
terra-list                         2.5.0  2.32.0  4.16.0  cds-hooks-sandbox
terra-menu                         2.5.0   2.8.0  6.10.0  cds-hooks-sandbox
terra-modal                        2.4.0   2.5.0   2.5.0  cds-hooks-sandbox
terra-overlay                      2.1.0  2.37.0  3.26.0  cds-hooks-sandbox
terra-responsive-element           2.4.0  2.12.0   5.7.0  cds-hooks-sandbox
terra-spacer                       2.4.0  2.33.0  3.19.0  cds-hooks-sandbox
terra-text                         2.4.0  2.32.0  4.15.0  cds-hooks-sandbox
terra-toggle                       2.1.0  2.31.0  3.19.0  cds-hooks-sandbox
```

**Comment by kolkheang** [comment]
Thanks @jmandel!  I agree that we can get this first major updates reviewed and merged even with the remaining dependencies still to be updated.

Locally, I have all except 2 dependencies up to date.  I working on configuring `webpack` and other things that require new configuration due to major versions/breaking changes.  I'll take care of updating remaining dependencies.

**Comment by jmandel** [comment]
Great, thanks @kolkheang!

> Locally, I have all except 2 dependencies up to date. I working on configuring webpack and other things that require new configuration

I think I have the lastest webpack set up here, but your config may indeed be more robust ;-) I basically just tweaked / updated until it worked.

**Review by kolkheang — APPROVED** [review]
Thanks @jmandel !

**Pull request merged**
