### PR TITLE
Enhanced Patient Selection

### PR DESCRIPTION
**Pull request by c-schuler**
Updated patient selection to be a dropdown list populated by patients in the current FHIR server

Here is a screen recording of the update:

https://github.com/user-attachments/assets/f257848a-36da-4147-83ea-cd05a14eeedb

### CODE REVIEW

**Comment by c-schuler** [comment]
@jmandel Another one for ya to review! Thanks in advance!

**Comment by jmandel** [comment]
Thanks for this! How much trouble would it be to include the Name + DOB in the selection process?

**Comment by c-schuler** [comment]
Nice idea @jmandel !

Here is the screen recording with that feedback applied:

https://github.com/user-attachments/assets/09ed4bde-c723-4ffb-8d4f-929124e0320f

**Comment by c-schuler** [comment]
@jmandel Please let me know if there are any other updates you'd like to see with this PR. Trying to get this pulled in for an AMIA demo if possible.

**Comment by c-schuler** [comment]
@jmandel I included a small fix for the prefetch resolution using POST logic in this PR. Hopefully that is ok. Happy to create another PR for the fix.

**Review by jmandel — APPROVED** [review]

**Comment by jmandel** [comment]
This is merged but note that it is not yet deployed @c-schuler because the build failed at 

```
> cds-hooks-sandbox@0.1.0 lint /home/runner/work/sandbox/sandbox
> eslint --ext .js,.jsx ./src --fix


/home/runner/work/sandbox/sandbox/src/components/PatientSelect/patient-select.jsx
Error:   41:3   error  Prop type "array" is forbidden         react/forbid-prop-types
Error:   56:49  error  'inputName' is defined but never used  no-unused-vars

/home/runner/work/sandbox/sandbox/src/retrieve-data-helpers/all-patient-retrieval.js
Error:   24:9  error  iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations  no-restricted-syntax
```

**Comment by c-schuler** [comment]
Understood. Applying resolution in #157

**Pull request merged**
